# Dependencies
#
import glfw = glfw%lib{glfw}
import igl_opengl = libigl-opengl%lib{igl-opengl}

# Header-Only Library
#
./: lib{igl-glfw}: igl/opengl/glfw/{hxx ixx}{*} $glfw $igl_opengl
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $glfw $igl_opengl
}

# Build Options
#
cxx.poptions =+ "-I$src_root"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{igl-glfw}: bin.lib.version = "-$version.project_id"
else
  liba{igl-glfw}: bin.lib.version = "-$version.major.$version.minor"

# Mark header and inclusion files as to be installed.
# Inclusion files are only installed when depending on lib{igl-core}.
#
{hxx ixx}{*}: install = include/igl/opengl/glfw/

./: manifest legal{LICENSE*} doc{*.md}
./: tests/: install = false
