# Dependencies
#
import glfw = glfw%lib{glfw}

# Header-Only Library
#
import igl_opengl = libigl-opengl%lib{igl-opengl}
./: lib{igl-glfw}: igl/opengl/glfw/{hxx ixx}{*} $glfw $igl_opengl
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $glfw $igl_opengl
}

# Precompiled Static Library
#
# The dependency 'liba{igl-core-compiled}'
# already exports the macro 'IGL_STATIC_LIBRARY'.
#
import igl_opengl_compiled = libigl-opengl%liba{igl-opengl-compiled}
./: liba{igl-glfw-compiled}: igl/opengl/glfw/{hxx cxx}{*} $glfw $igl_opengl_compiled
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $glfw $igl_opengl_compiled
}

# Build Options
#
cxx.poptions =+ "-I$src_root"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{igl-glfw-compiled}: bin.lib.version = "-$version.project_id"
else
  liba{igl-glfw-compiled}: bin.lib.version = "-$version.major.$version.minor"

# Mark header and inclusion files as to be installed.
# Inclusion files are only installed when depending on lib{igl-core}.
#
{hxx ixx}{*}: install = include/igl/opengl/glfw/

./: manifest legal{LICENSE*} doc{*.md}
./: tests/: install = false
