./: manifest legal{LICENSE*} doc{*.md} data/file{**}

# Currently, not all modules of libigl are supported.
# So, not all tutorials can be build.
# See: /upstream/libigl/tutorial/CMakeLists.txt
#
# 113 Shadows: The 'imgui' module is not needed.
#
./: {1*/ -109*/}
./: {2*/}
./: {3*/}
./: {4*/}
./: {5*/ -504*/ -505*/ -506*/}
./: {7*/ -706*/ -710*/ -714*/ -715*/ -717*/}

# No tutorial of chapter six is currently supported.
#
# ./: {6*/}
