import imgui = libimgui-platform-glfw%lib{imgui-platform-glfw}
import imgui += libimgui-render-opengl3%lib{imgui-render-opengl3}
import igl_glfw = libigl-glfw%lib{igl-glfw}

./: lib{igl-imgui}: igl/opengl/glfw/imgui/{hxx ixx}{*} backends/{hxx ixx}{*} {hxx ixx}{*} $imgui $igl_glfw
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $imgui $igl_glfw
}

cxx.poptions =+ "-I$src_root"

{hxx ixx}{*}: install = include/igl/opengl/glfw/imgui/

./: manifest legal{LICENSE*} doc{*.md}
./: tests/: install = false
