# Default Targets and Package Files
#
./: liba{igl-opengl} manifest legal{LICENSE*} doc{*.md}
./: tests/: install = false

# Imports
#
# Make sure the build is consistently setting precompilation
# by reading the metadata from the libigl module dependency.
#
import! [metadata, rule_hint=cxx.link] igl = libigl-core%liba{igl-core}
header_only = [bool] $($igl: libigl_core.header_only)
#
libs = $igl
import libs += libigl-glad%liba{igl-glad}

# Headers
#
liba{igl-opengl}: igl/opengl/hxx{* *.hpp}

# Sources
#
{ixx cxx}{*}: dist = false
src_files = igl/opengl/{*.cpp *.c}
./: file{$src_files}
#
liba{igl-opengl}: cxx{$src_files}: include = (!$header_only)
liba{igl-opengl}: ixx{$src_files}: include = $header_only

# Dependencies
#
liba{igl-opengl}: $libs
liba{igl-opengl}: cxx.export.libs = $libs

# Build and Export Options
#
liba{igl-opengl}: cxx.export.poptions = "-I$src_root"
cxx.poptions =+ "-I$src_root"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{igl-opengl}: bin.lib.version = "-$version.project_id"
else
  liba{igl-opengl}: bin.lib.version = "-$version.major.$version.minor"

# Library Metadata
#
liba{igl-opengl}:
{
  export.metadata = 1 libigl_opengl
  libigl_opengl.header_only = [bool] $header_only
}

# Mark header and inclusion files as to be installed.
# Inclusion files are only installed when no precompilation is used.
#
{hxx ixx}{*}: install = include/igl/opengl/
