import libs += libigl-core%lib{igl-core}

# The test executable must be named like this.
# Otherwise, one of the unit tests will fail.
#
exe{test_igl_core}: ../hxx{test_common} {hxx cxx}{*} igl/{hxx cxx}{*} $libs ../testscript

if ($cxx.target.system == 'win32-msvc')
  cxx.coptions += /bigobj
