import libs = libigl-opengl%lib{igl-opengl}
import libs += stb_image%lib{stb_image}
import libs += stb_image_write%lib{stb_image_write}

./: lib{igl-png}: cxx{*} igl/png/{hxx ixx}{*} $libs
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $libs
}

{hxx ixx}{*}: install = include/igl/png/

./: manifest legal{LICENSE*} doc{*.md}
./: tests/: install = false
