# Currently, not all modules of libigl are supported.
# So, not all tutorials can be build.
# See: /upstream/libigl/tutorial/CMakeLists.txt
#
./: {1*/ -105*/ -106*/ -109*/ -112*/}
./: {2*/}
./: {3*/}
./: {4*/ -409*/}
./: {5*/ -504*/ -505*/ -506*/}
./: {7*/ -706*/ -710*/ -714*/ -715*/ -717*/ -723*/ -724*/}

# No tutorial of chapter six is currently supported.
#
# ./: {6*/}
