# Default Targets
#
./: liba{igl-glfw}

# Imports
#
# Make sure the build is consistently setting precompilation
# by reading the metadata from the libigl module dependency.
#
import! [metadata, rule_hint=cxx.link] igl = libigl-opengl%liba{igl-opengl}
header_only = [bool] $($igl: libigl_opengl.header_only)
#
libs = $igl
import libs += glfw%lib{glfw}

# Headers
#
liba{igl-glfw}: igl/opengl/glfw/hxx{* *.hpp}

# Sources
#
{ixx cxx}{*}: dist = false
src_files = igl/opengl/glfw/{*.cpp *.c}
./: file{$src_files}
#
liba{igl-glfw}: cxx{$src_files}: include = (!$header_only)
liba{igl-glfw}: ixx{$src_files}: include = $header_only

# Dependencies
#
liba{igl-glfw}: $libs
liba{igl-glfw}: cxx.export.libs = $libs

# Build and Export Options
#
liba{igl-glfw}: cxx.export.poptions = "-I$src_base"
cxx.poptions =+ "-I$src_base"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  liba{igl-glfw}: bin.lib.version = "-$version.project_id"
else
  liba{igl-glfw}: bin.lib.version = "-$version.major.$version.minor"

# Library Metadata
#
liba{igl-glfw}:
{
  export.metadata = 1 libigl_glfw
  libigl_glfw.header_only = [bool] $header_only
}

# Mark header and inclusion files as to be installed.
# Inclusion files are only installed when depending on lib{igl-core}.
#
{hxx ixx}{*}: install = include/igl/opengl/glfw/
